// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_BCMExBBNq3yDulJiNAJ7z2O-oDs4zX8',
    appId: '1:729446985504:web:3153a3635b95eee1f2b145',
    messagingSenderId: '729446985504',
    projectId: 'freelacarga',
    authDomain: 'freelacarga.firebaseapp.com',
    storageBucket: 'freelacarga.firebasestorage.app',
    measurementId: 'G-VK8G2GJP8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ9yqY0KOtOXhht7L32zPKcqpksjvv7ys',
    appId: '1:729446985504:android:286887225022ff96f2b145',
    messagingSenderId: '729446985504',
    projectId: 'freelacarga',
    storageBucket: 'freelacarga.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-YZeAxJISnW8iDKEt0B6MBZjhi5dXkIY',
    appId: '1:729446985504:ios:f5929b2367fdf26df2b145',
    messagingSenderId: '729446985504',
    projectId: 'freelacarga',
    storageBucket: 'freelacarga.firebasestorage.app',
    iosBundleId: 'com.renanbezerra.freelaCarga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-YZeAxJISnW8iDKEt0B6MBZjhi5dXkIY',
    appId: '1:729446985504:ios:f5929b2367fdf26df2b145',
    messagingSenderId: '729446985504',
    projectId: 'freelacarga',
    storageBucket: 'freelacarga.firebasestorage.app',
    iosBundleId: 'com.renanbezerra.freelaCarga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_BCMExBBNq3yDulJiNAJ7z2O-oDs4zX8',
    appId: '1:729446985504:web:e7ba1520d7ef6b11f2b145',
    messagingSenderId: '729446985504',
    projectId: 'freelacarga',
    authDomain: 'freelacarga.firebaseapp.com',
    storageBucket: 'freelacarga.firebasestorage.app',
    measurementId: 'G-QFRXZP087Q',
  );
}
